#!/bin/bash
python main.py --target_domain="AddToPlaylist"
python main.py --target_domain="AddToPlaylist" --run_mode="test"
python main.py --target_domain="BookRestaurant"
python main.py --target_domain="BookRestaurant" --run_mode="test"
python main.py --target_domain="GetWeather"
python main.py --target_domain="GetWeather" --run_mode="test"
python main.py --target_domain="PlayMusic"
python main.py --target_domain="PlayMusic" --run_mode="test"
python main.py --target_domain="RateBook"
python main.py --target_domain="RateBook" --run_mode="test"
python main.py --target_domain="SearchCreativeWork"
python main.py --target_domain="SearchCreativeWork" --run_mode="test"
python main.py --target_domain="SearchScreeningEvent"
python main.py --target_domain="SearchScreeningEvent" --run_mode="test"